[book]
title = "学习 eBPF"
language = "zh-CN"
git-repository-url = "https://github.com/binw666/learning-ebpf-translation"
# alerts 扩展支持
[preprocessor.alerts]
# 支持侧边目录
[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
